- layouts/default.vue
- middleware/auth.global.ts
- models/Meta.d.ts
- pages/@protected/admin.vue
- stores/authStore.ts
- tsconfig.json
- Extend route meta data types.
- Add accessLevel getter to auth store to check the users accessLevel.
- Update route middleware to check accessLevel.
> feat: access-level middleware

- components/nav/Horizontal.vue
- components/nav/Vertical.vue
- composables/useFirebaseAuth.ts
- middleware/auth.global.ts
- models/Meta.d.ts
- models/User.ts
- pages/admin.vue
- server/api/user/index.delete.ts
- server/api/user/index.post.ts
- server/api/user/index.ts
- server/utils/hasAccess.ts
- server/utils/hasAccessLevel.ts
- stores/appStore.ts
- stores/authStore.ts
- Change implementation of access levels and user types as described in issue #85.
- Move global state `registeringUser` from _appStore_ to _authStore_.
> refactor: access levels and user types

- components/company/Hero.vue
- locales/en-US.json
- locales/nb-NO.json
- pages/index.vue
First draft for the CompanyHero component
On computer screen, the component is a sheet that is divided in the middle,  with the company logo is on the left, and the rest of the info on the right. So far, there is no styling that ensures that the height of the logo and the height of the info are close to each other; thus, if for instance the company logo is wide and short, the component looks somewhat disproportionate.
On mobile, the logo goes on top, and the company info directly underneath. 
In order to render the component on the home page, add this code to **~/pages/index.vue**
```html
<CompanyHero
:content="{
name: 'Companyname',
description: ``,
logo: [ logoUrl ],
website: 'https://shortsdag.no',
}"
class="my-5 d-flex justify-center"
/>
```
just add some Lorem Ipsum into the …
> feat: companyhero component

- components/footer/Index.vue
* Conditionally rendering email icon based on viewport width
> fix: omit render of email icon on md breakpoint and lower

- README.md
* Updating "Getting started" documentation
* Changing all use of npm to pnpm
* Fixing broken WIKI link
> docs: updating README

- pages/index.vue
* Updating _main sponsor_ value in `pages/index.vue` to _main partner_.
* Updating company type value to `main-partner`
> fix: changing main sponsor to main partner

- components/common/Grid.vue
- pages/index.vue
* Renaming CompanyGrid component to CommonGrid
* Setting display to flex with centering alignment
> fix: changing flex align to center

- components/footer/Index.vue
* Adding address to footer as it is required by law.
> feat: adding organisation address to footer

- config/app.config.ts
- locales/en-US.json
- locales/nb-NO.json
- models/Job.ts
- pages/admin/jobs.vue
- server/api/job/index.post.ts
* Listing Jobs in admin panel with relevant information
* Ability to edit jobs from `/admin/jobs`
> feat: job admin page

- components/job/Card.vue
- components/programme/Timeline.vue
- pages/event/[id].vue
* Removing card actions in programme/Timeline component
* Adding sign-up/opt-out functionality to `event/[id]` route
* Adding card elevation to communicate clickable card to mobile users
> refactor: concise mobile actions

- locales/en-US.json
- locales/nb-NO.json
- pages/jobs/[id].vue
- pages/jobs/[job].vue
- Job page
- Add application link to Jobs, this includes updating CMS, API endpoints and database entries.
> feat: job page

- nuxt.config.ts
* Adding static page title to nuxt config
> feat: static page title

- locales/en-US.json
- locales/nb-NO.json
- models/User.ts
- pages/user/index.vue
* Adding new user page info card
> feat: user page

- components/event/EditForm.vue
* Admins can create self-hosted events
> feat: etdagene options in event edit

- components/event/EditForm.vue
- components/form/DateTimeInput.vue
- components/job/EditForm.vue
- composables/useDate.ts
- Add date time input component.
- Update event and job edit pages accordingly.
> feat: date time input

- components/locale/Switcher.vue
- components/user/EditForm.vue
- package.json
- pnpm-lock.yaml
- Import types using `import type`.
- Update i18n module.
- Remove !important statement from edit user page width, as this was causing some trouble.
> fix: import types with type

- components/home/Banner.vue
- components/job/Card.vue
- components/programme/Timeline.vue
- composables/useDate.ts
- pages/jobs/[id].vue
* Get month string function now gets internationalisation string explicitly
* Using day and month string function, but adding a month truncate bool
> refactor: month string in timeline tab

- components/footer/Index.vue
* Removing GH icon
* Change study programme link to the norwegian
* Correcting organisation name
> refactor: footer component

- components/job/Card.vue
- components/job/EditForm.vue
- locales/en-US.json
- locales/nb-NO.json
- pages/admin/jobs.vue
- pages/jobs/[id].vue
- pages/user/index.vue
- server/api/job/index.post.ts
- Add optional `applicationLink` to Jobs. This includes updating the API endpoints and edit page.
- Fix error in /admin/jobs when no jobs are found.
- Display job type on /job page.
> feat: job application link

- components/company/EditForm.vue
- components/event/EditForm.vue
- components/job/EditForm.vue
- components/nav/Horizontal.vue
- components/nav/Vertical.vue
- components/programme/Timeline.vue
- components/user/EditForm.vue
- composables/useDate.ts
- locales/en-US.json
- locales/nb-NO.json
- pages/company/admin.vue
- pages/user/edit/index.vue
- server/api/company/events/index.ts
- server/api/user/index.ts
* Company users can see all their events
* Company users can edit self owned events
* composables fetches i18n strings by them selves
> feat: company event info

- components/programme/Timeline.vue
* Formating timeline tabs to string
> chore: format to string in tab

- pages/event/[id].vue
- Remove registration start/stop display if there is no capacity limit on the event.
- Fixed a localization error on event page.
> fix: conditional render of registration start display

- components/event/EditForm.vue
> fix: adding capacity to existing event

- components/programme/Timeline.vue
* Sorting date tabs in timeline component in correct order
> fix: date tab sorting

- components/form/SelectInput.vue
- components/user/EditForm.vue
- components/user/SignupForm.vue
- config/app.config.ts
- locales/en-US.json
- locales/nb-NO.json
* Registering user are now allowed to only submit custom allergy if not in list
* Study programme and allergy dropdowns are now sorted alphabetically
> fix: 323 force allergy input on custom

- components/common/Grid.vue
- components/home/CountDown.vue
- pages/index.vue
> feat: styling adjustments on home page

- components/company/EditForm.vue
- components/event/EditForm.vue
- components/form/RichTextInput.vue
- components/job/Card.vue
- components/job/EditForm.vue
- locales/en-US.json
- locales/nb-NO.json
- package.json
- pages/event/[id].vue
- pages/jobs/[id].vue
- pnpm-lock.yaml
* Using Tiptap rich text editor to add event and job descriptions
* Rendering descriptions as html in /jobs/[id] and /event/[id].
This fixes #337.
> refactor: rich text support for description

- components/common/Modal.vue
- components/programme/Timeline.vue
* Changing image size to 75% of container width
> refactor: changing stand map image with

- locales/en-US.json
- locales/nb-NO.json
- pages/event/[id].vue
* Opting out now requires confirmation in a dialog box
> feat: confirm event opt out

- assets/scss/main.scss
- locales/en-US.json
- locales/nb-NO.json
- pages/user/index.vue
- Add a simple list of events on the user page.
> feat: add event list to user page

- app.vue
- Keep alive pages to preserve state when navigating between pages.
> feat: keepalive pages

- components/footer/Index.vue
- locales/en-US.json
- locales/nb-NO.json
- Add social media links to footer.
> feet: add some links in the footer

- components/job/Card.vue
* You can now open jobs in new tab, allowing for opening multiple at once from /jobs
> feat: job card nuxtlink

- locales/en-US.json
- locales/nb-NO.json
- pages/index.vue
* English slogan in `HomeBanner`
> feat: i18n banner slogan

- pages/jobs/index.vue
* Jobs are now sorted showing closes deadline first, by default
> default sorting order for jobs

- components/company/EditForm.vue
- components/user/EditForm.vue
- locales/en-US.json
- locales/nb-NO.json
- pages/user/signin.vue
* Using new alert system on user edit
* Removing user edit query message on `/user/signin`
> fix: deprecated alert system for user/edit

- components/form/RichTextInput.vue
- components/programme/Timeline.vue
- pages/event/[id].vue
- pages/jobs/[id].vue
* New edit button on `/event/[id]` and `/jobs/[id]`.
> edit event in place

- app.vue
- package.json
- pages/jobs/index.vue
- pages/programme.vue
- pnpm-lock.yaml
* Only keeping alive `/programme`
* Bump nuxt version to `3.10`
> fix: keep alive

- components/event/AttendantsList.vue
- pages/event/[id].vue
Add AttendantsList component with pagination to list the current attendants for an event
> GUI for event participants
